# Generated by Django 4.2.2 on 2024-06-21 08:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_coverage_MCDC', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, max_length=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('percent_coverage_Analysis', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, max_length=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_coverage', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, max_length=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='defectClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(choices=[('Yes', 'Y'), ('No', 'N'), ('', 'Null')], default='', max_length=20)),
                ('non_tech', models.CharField(choices=[('Yes', 'Y'), ('No', 'N'), ('', 'Null')], default='', max_length=20)),
                ('process', models.CharField(choices=[('Yes', 'Y'), ('No', 'N'), ('', 'Null')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='moduleStrucData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branches', models.IntegerField()),
                ('pairs', models.IntegerField()),
                ('statement', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SCGAFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=200)),
                ('analyst', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('oversight', models.CharField(choices=[('Yes', 'Y'), ('No', 'N'), ('', 'Null')], default='', max_length=20)),
                ('note', models.CharField(max_length=200)),
                ('uncoverage_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SCGAModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=200)),
                ('process', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='testException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='testPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='uncoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uncovered_sw_line', models.IntegerField()),
                ('uncovered_instrument_sw_line', models.TextField(default='')),
                ('requirement_id', models.CharField(max_length=200)),
                ('_class', models.CharField(choices=[('Incomplete Tests', 'Incomplete Tests'), ('Requirements-Code Mismatch', 'Requirements-Code Mismatch'), ('Deactivated Code', 'Deactivated Code'), ('Defensive Code', 'Defensive Code'), ('Test Environment Limitations', 'Test Environment Limitations'), ('Previously Analyzed Software', 'Previously Analyzed Software'), ('Other', 'Other')], default='', max_length=200)),
                ('analysis_summary', models.CharField(default='', max_length=200)),
                ('correction_summary', models.CharField(default='', max_length=200)),
                ('issue', models.CharField(choices=[('Yes', 'Y'), ('No', 'N'), ('', 'Null')], default='', max_length=20)),
                ('PAR_SCR', models.CharField(default='N/A', max_length=200)),
                ('comment', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='scga',
            name='baseline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scga',
            name='file_name',
            field=models.CharField(max_length=200),
        ),
    ]
