# Generated by Django 4.2 on 2024-06-23 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0009_lvtotalcoverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexception',
            name='scga_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_exceptions', to='scgaapi.scga'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='scga_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='scgaapi.scga'),
        ),
        migrations.AlterField(
            model_name='testexception',
            name='level',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('unkown', 'Unknown')], default='unkown', max_length=20),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='level',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('unkown', 'Unknown')], default='unkown', max_length=20),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
