# Generated by Django 5.0.6 on 2024-06-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0012_alter_defectclassification_non_tech_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('NA', 'NA')], default='NA', max_length=20)),
            ],
        ),
    ]
