# Generated by Django 5.0.6 on 2024-07-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0019_alter_defectclassification_non_tech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uncoverage',
            name='uncovered_sw_line',
            field=models.CharField(max_length=255),
        ),
    ]
