# Generated by Django 5.0.6 on 2024-07-03 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0021_alter_scgamodule_test_exception_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scgamodule',
            name='test_exception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='scgaapi.testexception'),
        ),
        migrations.AlterField(
            model_name='scgamodule',
            name='test_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='scgaapi.testplan'),
        ),
    ]
