# Generated by Django 5.0.6 on 2024-07-03 01:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0022_alter_scgamodule_test_exception_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='percent_coverage_Analysis',
            field=models.DecimalField(decimal_places=20, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='percent_coverage_MCDC',
            field=models.DecimalField(decimal_places=20, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='total_coverage',
            field=models.DecimalField(decimal_places=20, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lvtotalcoverage',
            name='percent_coverage_Analysis',
            field=models.DecimalField(decimal_places=20, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lvtotalcoverage',
            name='percent_coverage_MCDC',
            field=models.DecimalField(decimal_places=20, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lvtotalcoverage',
            name='total_coverage',
            field=models.DecimalField(decimal_places=20, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
