# Generated by Django 5.0.6 on 2024-07-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0027_alter_defectclassification_non_tech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uncoverage',
            name='_class',
            field=models.CharField(choices=[('', ''), ('INCOMPLETE_TESTS', 'Incomplete Tests'), ('REQUIREMENTS_CODE_MISMATCH', 'Requirements-Code Mismatch'), ('DEACTIVATED_CODE', 'Deactivated Code'), ('DEFENSIVE_CODE', 'Defensive Code'), ('TEST_ENVIRONMENT_LIMITATIONS', 'Test Environment Limitations'), ('PREVIOUSLY_ANALYZED_SOFTWARE', 'Previously Analyzed Software'), ('OTHER', 'Other')], default='', max_length=255),
        ),
    ]
