# Generated by Django 5.0.6 on 2024-07-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0029_alter_coverage_percent_coverage_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scga',
            name='baseline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scga',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='scgamodule',
            name='module_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scgamodule',
            name='process',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='branches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='pairs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='statement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
