# Generated by Django 5.0.6 on 2024-07-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0030_alter_level_level_alter_scga_baseline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='scga_file',
            new_name='scga',
        ),
    ]
