# Generated by Django 5.1.2 on 2024-11-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0031_rename_scga_file_level_scga'),
    ]

    operations = [
        migrations.AddField(
            model_name='scga',
            name='current',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=5, null=True),
        ),
    ]
