# Generated by Django 5.1.2 on 2024-11-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0032_scga_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scga',
            name='current',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='Y', max_length=5, null=True),
        ),
    ]
