# Generated by Django 5.1.2 on 2024-11-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0033_alter_scga_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='scga',
            name='function',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scga',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
