# Generated by Django 5.1.2 on 2024-11-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0034_scga_function_scga_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uncoverage',
            name='analysis_summary',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='correction_summary',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='requirement_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='uncovered_sw_line',
            field=models.TextField(blank=True, null=True),
        ),
    ]
