# Generated by Django 4.2 on 2024-06-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0003_covered_total_delete_modulestrucdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexception',
            name='scga_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testExceptions', to='scgaapi.scga'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='scga_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testPlans', to='scgaapi.scga'),
        ),
    ]
