# Generated by Django 4.2 on 2024-06-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0004_testexception_scga_file_testplan_scga_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectclassification',
            name='non_tech',
            field=models.CharField(choices=[('yes', 'Y'), ('no', 'N'), ('', 'Null')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='defectclassification',
            name='process',
            field=models.CharField(choices=[('yes', 'Y'), ('no', 'N'), ('', 'Null')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='defectclassification',
            name='tech',
            field=models.CharField(choices=[('yes', 'Y'), ('no', 'N'), ('', 'Null')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='scga',
            name='baseline',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scga',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scgafunction',
            name='analyst',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scgafunction',
            name='function_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scgafunction',
            name='note',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scgafunction',
            name='oversight',
            field=models.CharField(choices=[('yes', 'Y'), ('no', 'N'), ('', 'Null')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='scgafunction',
            name='site',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scgamodule',
            name='module_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scgamodule',
            name='process',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testexception',
            name='level',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('unkown', 'Unknown')], default='unkown', max_length=20),
        ),
        migrations.AlterField(
            model_name='testexception',
            name='sheet_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='level',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('unkown', 'Unknown')], default='unkown', max_length=20),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='sheet_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='PAR_SCR',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='_class',
            field=models.CharField(choices=[('incomplete Tests', 'Incomplete Tests'), ('requirements-code mismatch', 'Requirements-Code Mismatch'), ('deactivated code', 'Deactivated Code'), ('defensive code', 'Defensive Code'), ('test environment limitations', 'Test Environment Limitations'), ('previously analyzed software', 'Previously Analyzed Software'), ('other', 'Other')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='analysis_summary',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='correction_summary',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='issue',
            field=models.CharField(choices=[('yes', 'Y'), ('no', 'N'), ('', 'Null')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='requirement_id',
            field=models.CharField(max_length=255),
        ),
    ]
