# Generated by Django 4.2 on 2024-06-23 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0005_alter_defectclassification_non_tech_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverage',
            name='function',
        ),
        migrations.RemoveField(
            model_name='defectclassification',
            name='unction',
        ),
        migrations.RemoveField(
            model_name='testexception',
            name='level',
        ),
        migrations.RemoveField(
            model_name='testexception',
            name='scga_file',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='level',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='scga_file',
        ),
        migrations.AddField(
            model_name='coverage',
            name='coverage_function_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverage', to='scgaapi.scgafunction'),
        ),
        migrations.AddField(
            model_name='defectclassification',
            name='function',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defect_classification', to='scgaapi.scgafunction'),
        ),
        migrations.AlterField(
            model_name='covered',
            name='function',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='covered', to='scgaapi.scgafunction'),
        ),
        migrations.AlterField(
            model_name='total',
            name='function',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='total', to='scgaapi.scgafunction'),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('unkown', 'Unknown')], default='unkown', max_length=20)),
                ('scga_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='scgaapi.scga')),
            ],
        ),
        migrations.AddField(
            model_name='testexception',
            name='te_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_exceptions', to='scgaapi.level'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='tp_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='scgaapi.level'),
        ),
    ]
