# Generated by Django 4.2 on 2024-06-23 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0006_remove_coverage_function_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverage',
            old_name='coverage_function_name',
            new_name='function',
        ),
    ]
