# Generated by Django 4.2 on 2024-06-23 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0007_rename_coverage_function_name_coverage_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testexception',
            name='te_level',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='tp_level',
        ),
        migrations.AddField(
            model_name='testexception',
            name='level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_exception', to='scgaapi.level'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_plan', to='scgaapi.level'),
        ),
    ]
