# Generated by Django 4.2 on 2024-06-23 05:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0008_remove_testexception_te_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LvTotalCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_coverage_MCDC', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, max_length=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('percent_coverage_Analysis', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, max_length=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_coverage', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, max_length=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('test_plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lv_total_coverage', to='scgaapi.testplan')),
            ],
        ),
    ]
