# Generated by Django 4.2 on 2024-06-23 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0010_testexception_scga_file_testplan_scga_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scga',
            name='file_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='testexception',
            name='scga_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_exceptions', to='scgaapi.scga', to_field='file_name'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='scga_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='scgaapi.scga', to_field='file_name'),
        ),
    ]
