# Generated by Django 5.0.6 on 2024-06-25 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0013_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testexception',
            name='scga_file',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='scga_file',
        ),
        migrations.AddField(
            model_name='level',
            name='scga_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='scgaapi.scga'),
        ),
        migrations.AlterField(
            model_name='testexception',
            name='level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_exception', to='scgaapi.level'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='scgaapi.level'),
        ),
    ]
