# Generated by Django 5.0.6 on 2024-07-01 09:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0017_alter_uncoverage_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='percent_coverage_Analysis',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='percent_coverage_MCDC',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='total_coverage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='defectclassification',
            name='non_tech',
            field=models.CharField(choices=[('NA', 'NA'), ('Y', 'Y'), ('N', 'N')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='defectclassification',
            name='process',
            field=models.CharField(choices=[('NA', 'NA'), ('Y', 'Y'), ('N', 'N')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='defectclassification',
            name='tech',
            field=models.CharField(choices=[('NA', 'NA'), ('Y', 'Y'), ('N', 'N')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(choices=[('NA', 'NA'), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='lvtotalcoverage',
            name='percent_coverage_Analysis',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lvtotalcoverage',
            name='percent_coverage_MCDC',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lvtotalcoverage',
            name='total_coverage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='scgafunction',
            name='oversight',
            field=models.CharField(choices=[('NA', 'NA'), ('Y', 'Y'), ('N', 'N')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='_class',
            field=models.CharField(choices=[('NA', 'NA'), ('incomplete Tests', 'Incomplete Tests'), ('requirements-code mismatch', 'Requirements-Code Mismatch'), ('deactivated code', 'Deactivated Code'), ('defensive code', 'Defensive Code'), ('test environment limitations', 'Test Environment Limitations'), ('previously analyzed software', 'Previously Analyzed Software'), ('other', 'Other')], default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='issue',
            field=models.CharField(choices=[('NA', 'NA'), ('Y', 'Y'), ('N', 'N')], default='NA', max_length=20),
        ),
    ]
