# Generated by Django 5.0.6 on 2024-07-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0018_alter_coverage_percent_coverage_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectclassification',
            name='non_tech',
            field=models.CharField(choices=[('NA', 'NA'), ('Y', 'Y'), ('N', 'N')], default='NA', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='defectclassification',
            name='process',
            field=models.CharField(choices=[('NA', 'NA'), ('Y', 'Y'), ('N', 'N')], default='NA', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='defectclassification',
            name='tech',
            field=models.CharField(choices=[('NA', 'NA'), ('Y', 'Y'), ('N', 'N')], default='NA', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scgafunction',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scgafunction',
            name='oversight',
            field=models.CharField(choices=[('NA', 'NA'), ('Y', 'Y'), ('N', 'N')], default='NA', max_length=20, null=True),
        ),
    ]
