# Generated by Django 5.0.6 on 2024-07-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0025_alter_coverage_percent_coverage_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uncoverage',
            name='_class',
            field=models.CharField(choices=[('NA', 'NA'), ('INCOMPLETE_TESTS', 'Incomplete Tests'), ('REQUIREMENTS_CODE_MISMATCH', 'Requirements-Code Mismatch'), ('DEACTIVATED_CODE', 'Deactivated Code'), ('DEFENSIVE_CODE', 'Defensive Code'), ('TEST_ENVIRONMENT_LIMITATIONS', 'Test Environment Limitations'), ('PREVIOUSLY_ANALYZED_SOFTWARE', 'Previously Analyzed Software'), ('OTHER', 'Other')], default='', max_length=255),
        ),
    ]
