# Generated by Django 5.0.6 on 2024-07-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0026_alter_uncoverage__class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectclassification',
            name='non_tech',
            field=models.CharField(choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='defectclassification',
            name='process',
            field=models.CharField(choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='defectclassification',
            name='tech',
            field=models.CharField(choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='scgafunction',
            name='oversight',
            field=models.CharField(choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='_class',
            field=models.CharField(choices=[('', 'NA'), ('INCOMPLETE_TESTS', 'Incomplete Tests'), ('REQUIREMENTS_CODE_MISMATCH', 'Requirements-Code Mismatch'), ('DEACTIVATED_CODE', 'Deactivated Code'), ('DEFENSIVE_CODE', 'Defensive Code'), ('TEST_ENVIRONMENT_LIMITATIONS', 'Test Environment Limitations'), ('PREVIOUSLY_ANALYZED_SOFTWARE', 'Previously Analyzed Software'), ('OTHER', 'Other')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='issue',
            field=models.CharField(choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=20),
        ),
    ]
