# Generated by Django 5.0.6 on 2024-07-08 09:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scgaapi', '0028_alter_uncoverage__class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='percent_coverage_Analysis',
            field=models.DecimalField(blank=True, decimal_places=19, default=Decimal('0.00'), max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='percent_coverage_MCDC',
            field=models.DecimalField(blank=True, decimal_places=19, default=Decimal('0.00'), max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='total_coverage',
            field=models.DecimalField(blank=True, decimal_places=19, default=Decimal('0.00'), max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='covered',
            name='branches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covered',
            name='pairs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covered',
            name='statement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defectclassification',
            name='non_tech',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='defectclassification',
            name='process',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='defectclassification',
            name='tech',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lvtotalcoverage',
            name='percent_coverage_Analysis',
            field=models.DecimalField(blank=True, decimal_places=19, default=Decimal('0.00'), max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lvtotalcoverage',
            name='percent_coverage_MCDC',
            field=models.DecimalField(blank=True, decimal_places=19, default=Decimal('0.00'), max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lvtotalcoverage',
            name='total_coverage',
            field=models.DecimalField(blank=True, decimal_places=19, default=Decimal('0.00'), max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='scgafunction',
            name='analyst',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scgafunction',
            name='function_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scgafunction',
            name='oversight',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scgafunction',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scgafunction',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scgafunction',
            name='uncoverage_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testexception',
            name='sheet_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='sheet_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='PAR_SCR',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='_class',
            field=models.CharField(blank=True, choices=[('', ''), ('INCOMPLETE_TESTS', 'Incomplete Tests'), ('REQUIREMENTS_CODE_MISMATCH', 'Requirements-Code Mismatch'), ('DEACTIVATED_CODE', 'Deactivated Code'), ('DEFENSIVE_CODE', 'Defensive Code'), ('TEST_ENVIRONMENT_LIMITATIONS', 'Test Environment Limitations'), ('PREVIOUSLY_ANALYZED_SOFTWARE', 'Previously Analyzed Software'), ('OTHER', 'Other')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='analysis_summary',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='correction_summary',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='issue',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='requirement_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='uncovered_instrument_sw_line',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='uncoverage',
            name='uncovered_sw_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
